# Creating DataFrames

Let’s look at different ways to create a Pandas `DataFrame` — the core data structure you’ll be using 90% of the time in data science.

---

## From Python Lists

```python
import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)
```

---

## From Dictionary of Lists

Most common and readable format:

```python
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
```

Each **key becomes a column**, and each list is the **column data**.

---

## From NumPy Arrays

```python
import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
```

Make sure to provide column names!

---

## From CSV Files

```python
df = pd.read_csv("data.csv")
```

Use options like:
- `sep`, `header`, `names`, `index_col`, `usecols`, `nrows`, etc.

Example:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"])
```

---

## From Excel Files

```python
df = pd.read_excel("data.xlsx")
```

You may need to install `openpyxl` or `xlrd`:
```bash
pip install openpyxl
```

---

## From JSON

```python
df = pd.read_json("data.json")
```

Can also read from a URL or string.

---

## From SQL Databases

```python
import sqlite3

conn = sqlite3.connect("mydb.sqlite")
df = pd.read_sql("SELECT * FROM users", conn)
```

---

## From the Web (Example: CSV from URL)

```python
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
```

---

## EDA (Exploratory Data Analysis)
Exploratory Data Analysis (EDA) is an essential first step in any data science project. 

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models. 

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

```python
df.head()         # First 5 rows
df.tail()         # Last 5 rows
df.info()         # Column info: types, non-nulls
df.describe()     # Stats for numeric columns
df.columns        # List of column names
df.shape          # (rows, columns)
```

---

## Summary

- You can create DataFrames from lists, dicts, arrays, files, web, and SQL  
- Use `.head()`, `.info()`, `.describe()` to quickly explore any dataset

In [1]:
import pandas as pd

In [2]:
data = [['yash', 45],['yash1', 78],['yash2', 98],['yash3', 67]]

In [3]:
data

[['yash', 45], ['yash1', 78], ['yash2', 98], ['yash3', 67]]

In [4]:
pd.DataFrame(data, columns = ['Name', 'Marks'])

    Name  Marks
0   yash     45
1  yash1     78
2  yash2     98
3  yash3     67

In [5]:
data = {"a":  [4,6,3], "b": [56,34,34]}

In [6]:
data

{'a': [4, 6, 3], 'b': [56, 34, 34]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   a   b
0  4  56
1  6  34
2  3  34

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[4,5]])

In [11]:
df = pd.DataFrame(arr, columns = ["A","B"])

In [12]:
df

   A  B
0  1  2
1  4  5