# Creating DataFrames

Let’s look at different ways to create a Pandas `DataFrame` — the core data structure you’ll be using 90% of the time in data science.

---

## From Python Lists

```python
import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)
```

---

## From Dictionary of Lists

Most common and readable format:

```python
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
```

Each **key becomes a column**, and each list is the **column data**.

---

## From NumPy Arrays

```python
import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
```

Make sure to provide column names!

---

## From CSV Files

```python
df = pd.read_csv("data.csv")
```

Use options like:
- `sep`, `header`, `names`, `index_col`, `usecols`, `nrows`, etc.

Example:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"])
```

---

## From Excel Files

```python
df = pd.read_excel("data.xlsx")
```

You may need to install `openpyxl` or `xlrd`:
```bash
pip install openpyxl
```

---

## From JSON

```python
df = pd.read_json("data.json")
```

Can also read from a URL or string.

---

## From SQL Databases

```python
import sqlite3

conn = sqlite3.connect("mydb.sqlite")
df = pd.read_sql("SELECT * FROM users", conn)
```

---

## From the Web (Example: CSV from URL)

```python
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
```

---

## EDA (Exploratory Data Analysis)
Exploratory Data Analysis (EDA) is an essential first step in any data science project. 

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models. 

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

```python
df.head()         # First 5 rows
df.tail()         # Last 5 rows
df.info()         # Column info: types, non-nulls
df.describe()     # Stats for numeric columns
df.columns        # List of column names
df.shape          # (rows, columns)
```

---

## Summary

- You can create DataFrames from lists, dicts, arrays, files, web, and SQL  
- Use `.head()`, `.info()`, `.describe()` to quickly explore any dataset

In [1]:
import pandas as pd

In [2]:
data = [['yash', 45],['yash1', 78],['yash2', 98],['yash3', 67]]

In [3]:
data

[['yash', 45], ['yash1', 78], ['yash2', 98], ['yash3', 67]]

In [4]:
pd.DataFrame(data, columns = ['Name', 'Marks'])

    Name  Marks
0   yash     45
1  yash1     78
2  yash2     98
3  yash3     67

In [5]:
data = {"a":  [4,6,3], "b": [56,34,34]}

In [6]:
data

{'a': [4, 6, 3], 'b': [56, 34, 34]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   a   b
0  4  56
1  6  34
2  3  34

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[4,5]])

In [11]:
df = pd.DataFrame(arr, columns = ["A","B"])

In [12]:
df

   A  B
0  1  2
1  4  5

In [13]:
pd.read_excel("data.xlsx")

    Name School  Marks
0  Yash1    DPS     98
1  Yash2    EPS     97
2  Yash3    FPS     96
3  Yash4    GPS     95
4  Yash5    HPS     94
5  Yash6    IPS     93
6  Yash7    JPS     92
7  Yash8    KPS     91
8  Yash9    LPS     90

In [14]:
df = pd.read_excel("data.xlsx")

In [15]:
df

    Name School  Marks
0  Yash1    DPS     98
1  Yash2    EPS     97
2  Yash3    FPS     96
3  Yash4    GPS     95
4  Yash5    HPS     94
5  Yash6    IPS     93
6  Yash7    JPS     92
7  Yash8    KPS     91
8  Yash9    LPS     90

In [16]:
df = pd.read_csv("data.csv")

In [17]:
df

    Name School  Marks
0  Yash1    DPS     98
1  Yash2    EPS     97
2  Yash3    FPS     96
3  Yash4    GPS     95
4  Yash5    HPS     94
5  Yash6    IPS     93
6  Yash7    JPS     92
7  Yash8    KPS     91
8  Yash9    LPS     90

In [18]:
df = pd.read_json("data.json")

In [19]:
df

     name    lang
0    Yash  Python
1  Yash12  Python

In [20]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [21]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 17.3 KB

In [25]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [26]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')